version: "3.5"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/dashboards
    ports:
      - 3000:3000

  coherence1:
    image: oraclecoherence/coherence-ce:21.06.1
    environment:
      - coherence.cluster=cluster1
      - coherence.member=member1
      - coherence.machine=machine1
      - coherence.site=Site1
      - coherence.metrics.http.enabled=true
    ports:
      - 30000:30000
      - 20000:20000
      - 1408:1408
      - 9612:9612

  coherence2:
    image: oraclecoherence/coherence-ce:21.06.1
    environment:
      - coherence.cluster=cluster1
      - coherence.member=member2
      - coherence.machine=machine2
      - coherence.site=Site1
      - coherence.metrics.http.enabled=true
    ports:
      - 9613:9612
